
export const FETCH_FAVS_REQUEST = 'FETCH_FAVS_REQUEST'
export const FETCH_FAVS_SUCCESS = 'FETCH_FAVS_SUCCESS'
export const FETCH_FAVS_FAILURE = 'FETCH_FAVS_FAILURE'
export const UPLOAD_FAVS_REQUEST = 'GET_FAVS_REQUEST'
export const UPLOAD_FAVS_SUCCESS = 'GET_FAVS_SUCCESS'
export const UPLOAD_FAVS_FAILURE = 'GET_FAVS_FAILURE'